version: '3.8'

services:
  fastapi:
    # Eliminamos 'build: .' porque la imagen ya viene lista de ECR
    image: fastapi-cicd-pipeline:latest
    container_name: fastapi_app
    ports:
      - "80:8000"
    restart: unless-stopped
    # Añadimos sección de environment por si tu app necesita configurar algo
    # environment:
    #   - DATABASE_URL=${DATABASE_URL}
    #   - ENV=production